CREATE USER auth_user WITH PASSWORD 'auth_password';

CREATE DATABASE auth_db OWNER auth_user;

create table users (
    is_active boolean not null,
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity primary key,
    updated_at timestamp(6) with time zone not null,
    role varchar(20) not null constraint users_role_check check (
        (role)::text = ANY (
            (
                ARRAY[
                    'ADMIN'::character varying,
                    'USER'::character varying,
                    'GUEST'::character varying
                ]
            )::text []
        )
    ),
    email varchar(255) not null unique,
    password_hash varchar(255) not null
);

INSERT INTO
    public.users (
        is_active,
        created_at,
        id,
        updated_at,
        role,
        email,
        password_hash
    )
VALUES (
        true,
        '2026-09-17 04:54:38.775517 +00:00',
        1,
        '2026-09-17 04:54:38.775546 +00:00',
        'USER',
        'user@example.com',
        '$2a$10$4OLhvAjQlpsLHVFRu2yexeKyv3D5hKXDpoFxfVJFSMTdlHL6m1CJe'
    );

alter table users owner to auth_user;

create table refresh_sessions (
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    revoked_at timestamp(6) with time zone,
    user_id bigint not null constraint fk9ndfh1op1iy3xuqyi6gxkseg0 references users,
    id uuid not null primary key,
    token_hash varchar(64) not null
);

alter table refresh_sessions owner to auth_user;